version: '3.7'

services:
  # Traefik reverse proxy
  traefik:
    image: traefik:v3.1
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
    ports:
      - "80:80"        # HTTP
      - "8080:8080"    # Traefik Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  # Auth Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.localhost`)"
      - "traefik.http.services.auth.loadbalancer.server.port=3000"
    ports:
      - "3001:3000" # Local access (optional)
    environment:
      - NODE_ENV=production

  # Billing Service
  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    container_name: billing-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.billing.rule=Host(`billing.localhost`)"
      - "traefik.http.services.billing.loadbalancer.server.port=3000"
    ports:
      - "3002:3000" # Local access (optional)
    environment:
      - NODE_ENV=production

  # Mail Service
  mail-service:
    build:
      context: ./mail-service
      dockerfile: Dockerfile
    container_name: mail-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mail.rule=Host(`mail.localhost`)"
      - "traefik.http.services.mail.loadbalancer.server.port=3000"
    ports:
      - "3003:3000" # Local access (optional)
    environment:
      - NODE_ENV=production

  # User Service
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user.rule=Host(`user.localhost`)"
      - "traefik.http.services.user.loadbalancer.server.port=3000"
    ports:
      - "3004:3000" # Local access (optional)
    environment:
      - NODE_ENV=production
